---

- name: Download SEP client from Artifactory
  win_get_url:
    url: "https://artrepo.domain.com/artifactory/Engineering_Installs/{{ sep }}"
    dest: C:\\sources\\ansible
    validate_certs: no
    force: no
    timeout: 90

- name: Install Symantec Client
  win_package:
    path: c:\sources\ansible\{{ sep }}
    product_id: '{{ pid }}'
    arguments: /s
    state: present
  register: task

- pause:
    minutes: 2

- name: Verify Symantec log that install is complete
  win_wait_for:
     path: 'c:\users\installer\appdata\local\temp\sep_inst.log'
     search_regex: 'Symantec Corporation. Installation success or error status: 0'


- name: Reboot server post SEP service validation
  win_reboot:
  when: task.changed

- name: Wait for server boot post reboot
  wait_for_connection:
    delay: 180
